language: node_js
node_js:
  - node
cache:
  npm: true
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .next
  on:
    branch: master
